
name: Angular App to Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Angular
      uses: actions/setup-node@v1.4.5
      with:
        node-version: 16.x
    
    - name: Restore dependencies
      run: npm install --force --production
      
    - name: Publish Angular App
      run: npm run build      

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: covid-data-analyzer-artifact
        path: ./dist/covid-data-analyzer

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download published artifact
      uses: actions/download-artifact@v2.0.10

    - name: Deploying to Azure App Service
      uses: azure/webapps-deploy@v2      
      with:
        app-name: covid-data-analyzer
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: covid-data-analyzer-artifact
    
