
name: Dotnet API to Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore ./CovidDataApi

    - name: Build
      run: dotnet build --no-restore ./CovidDataApi

    - name: Publish
      run: dotnet publish ./CovidDataApi -o dist/

    - uses: actions/upload-artifact@v2.2.4
      with:
        path: ./dist

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download published artifact
      uses: actions/download-artifact@v2.0.10

    - name: Deploying to Azure App Service
      uses: azure/webapps-deploy@v2      
      with:
        app-name: coviddata-api
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: artifact
  
    